### ISSUE TITLE
Add maximum values reached

### ISSUE THREAD

**Issue by squrppi** [Julian-B90/tachometer#13]
Maximum values reached would be useful in determining resource usage and thus planning container cloud deployment.

**Comment by Julian-B90** [comment]
I would also like to include a notification for example when the CPU value goes higher than 50%. 
What do you think of that @squrppi ?

**Comment by squrppi** [comment]
For me, this is mainly development environment. Thus recording the resource peaks helps when making resource limits in cloud. I am actually expecting my instances to use one cpu fully for their operation duration. I'm not saying this feature would not be useful to others, though.

**Comment by Julian-B90** [comment]
Hey @squrppi i have release a new version (v 0.0.8). Attention: the max values are not yet saved and are only valid for the current session.
