### ISSUE TITLE
Not able to install it in Windows Container

### ISSUE THREAD

**Issue by Shashankkt** [Julian-B90/tachometer#7]
When installing for windows container, it throws - 

![image](https://user-images.githubusercontent.com/129862325/232669759-1fffcd65-fae3-4a26-8549-54f637c4d728.png)

Any help?

**Comment by Julian-B90** [comment]
Hey @Shashankkt thank you for your issue. 

Can you please give some more contextual information?

- what is your Main System (wich Version)?
- what is your Docker-Desktop version?
- run docker --version and docker context ls

**Comment by Shashankkt** [comment]
I am running docker desktop in Windows 11, docker desktop version - 4.18.0, running docker desktop for Windows containers

**Comment by Shashankkt** [comment]
Any updates? I was able to install this when I switch to Linux Containers mode in Docker Desktop. Seems like it doesn't work with Windows containers mode in docker. 

The documentation for this library is not very clear. Probably should mention it very clearly that this will only work with Linux containers so that people don't waste their time in figuring out how to make it work in windows containers. Just feedback.

**Comment by Julian-B90** [comment]
@Shashankkt  thanks you for your feedback. I've been very busy the last few days, but I'll have another look until the weekend.

**Comment by Julian-B90** [comment]
@Shashankkt I think it is a general problem of the docker extension. On my windows machine I have to tried out to install an extension with windows container. But i get the same error on every extension. I have open a bug on "Docker Extensions SDK"

**Comment by Julian-B90** [comment]
Hey

**Comment by Julian-B90** [comment]
@Shashankkt Unfortunately, Windows containers are not yet supported

https://github.com/docker/extensions-sdk/issues/234#issuecomment-1515917291
