### ISSUE TITLE
Unexpected Application Error! 404 Not Found V 0.05

### ISSUE THREAD

**Issue by Julian-B90** [Julian-B90/tachometer#9]
On Windows 11 in Tachometer V 0.0.5 can´t open the extension and get the folling error 
```
Unexpected Application Error!
404 Not Found
```

**Comment by pedroroxo** [comment]
Also have the same problem

**Comment by waar19** [comment]
Same error
![Screenshot 2023-04-25 165810](https://user-images.githubusercontent.com/4492064/234413595-8d13bc8e-a94b-4891-b093-47bd5d454161.png)

**Comment by OzBrown** [comment]
I have the same error, uninstalled and restarted PC, then installed with same error, restarted PC and docker, still same issue. Can not seen any logs?? Just get 404 Not Found

**Comment by Julian-B90** [comment]
I have made a fix. Please update to V 0.0.6 when it is available.

I have use createBrowserRouter but in this envoirement its wrong you must use createMemoryRouter.
